export const LOGOUT = "LOGOUT";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const GET_STORY_FEED = "GET_STORY_FEED";
export const OPEN_STORY_MODAL = "OPEN_STORY_MODAL";
export const CLOSE_STORY_MODAL = "CLOSE_STORY_MODAL";
export const DISPLAY_STORY_BOARD_NODE = "DISPLAY_STORY_BOARD_NODE";

export const OPEN_CREATOR_MODAL = "OPEN_CREATOR_MODAL";
export const CLOSE_CREATOR_MODAL = "CLOSE_CREATOR_MODAL";