export const LOGOUT = "LOGOUT";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const OPEN_STORY_MODAL = "OPEN_STORY_MODAL";
export const CLOSE_STORY_MODAL = "CLOSE_STORY_MODAL";
export const DISPLAY_SB_NODE = "DISPLAY_SB_NODE";

export const OPEN_CREATOR_MODAL = "OPEN_CREATOR_MODAL";
export const CLOSE_CREATOR_MODAL = "CLOSE_CREATOR_MODAL";

export const OPEN_THEATER_MODAL = "OPEN_THEATER_MODAL";
export const CLOSE_THEATER_MODAL = "CLOSE_THEATER_MODAL";

export const OPEN_REACTOR_MODAL = "OPEN_REACTOR_MODAL";
export const CLOSE_REACTOR_MODAL = "CLOSE_REACTOR_MODAL";