export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const OPEN_STORY_MODAL = "OPEN_STORY_MODAL";
export const CLOSE_STORY_MODAL = "CLOSE_STORY_MODAL";
export const DISPLAY_STORY_BOARD_NODE = "SET_ON_DISPLAY_STORY_BOARD_NODE";
export const GET_STORY_FEED = "GET_STORY_FEED";