// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

import (
	"outstagram/server/controllers/usercontroller"
	"outstagram/server/repositories"
	"outstagram/server/services/userservice"
)

// Injectors from container.go:

func InitializeUserController() (*usercontroller.Controller, error) {
	db, err := ConnectDatabase()
	if err != nil {
		return nil, err
	}
	userRepository := userrepo.New(db)
	userService := userservice.New(userRepository)
	controller := usercontroller.New(userService)
	return controller, nil
}
